spring:

    datasource:
#        ?createDatabaseIfNotExist=true -> 존재 하지 않으면 생성
        url: jdbc:mysql://localhost:3306/roomshare?createDatabaseIfNotExist=true
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mariadb://svc.sel4.cloudtype.app:30385/roomshare?createDatabaseIfNotExist=true
        username: root
        password: test1234

    jpa:
        hibernate:
            ddl-auto: update

    profiles:
        include: secret

    output:
      ansi:
          enabled: always

    servlet:
            multipart:
                max-file-size: 1MB
                max-request-size: 10MB

logging:
    level:
        son: debug
        org:
            hibernate:
                sql: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder : trace

jwt:
    secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK


file:
    dir: C:/Users/admin/IdeaProjects/roomShare/src/main/resources/static/upload/